templates:
  torrent:
    transmission:
      main_file_only: yes
      include_subs: yes
      rename_like_files: yes
      ratio: 0
      skip_files:
        - '*.nfo'
        - '*.sfv'
        - '*.txt'
        - '*[sS]ample*'
        - 'RARBG.COM.mp4'
  
#notify:
#  entries:
#    via:
#      - notifymyandroid:
#          api_key: a6572f050fd85388e53d456e55925c48ebb8d06f002e74b5


tasks:
  get-tv:
    rss: <hereyourshowrrs>
    all_series:
      propers: no
    template: 
      - torrent
    thetvdb_lookup: yes
    set:
      content_filename: "{{ tvdb_series_name }}.S{{ tvdb_season|pad(2) }}E{{ tvdb_episode|pad(2) }}.{{ tvdb_ep_name|default('Missing title') }}"
      path: /home/pzotac/Downloads/Torrent/Complete/Series

  #task to pull movies from trakt.tv watchlist and add to the movie queue
  get-trakt_movies:
    priority: 1 # run before the movie search task
    trakt_list:
      username: <hereyourusername>
      list: watchlist
      type: movies
    imdb_watchlist:
      user_id: <hereryouruserid>
      list: watchlist
    accept_all: yes
    seen: yes
    list_add:
      - movie_list: traktmovies

  # task that automatically generates an rss feed based on entries from the movie_queue
  get-movies:
    priority: 10 # run after the movie queue fill task
    discover:
      what:
        - movie_list: traktmovies
      from:
        - rarbg:
            category: 
              - x264 720p
              - x264 1080p
            sorted_by: seeders
        - piratebay:
            category: "highres movies"
            sort_by: seeds
#        - 1337x:
#            order_by: seeders
        - limetorrents:
            category: movies
            order_by: seeds
        - yts: yes
#        - torrentz: good
#        - search_rss:
#            url: https://www.limetorrents.cc/searchrss/{{search_term}}
      interval: 4 hours
      release_estimations:
        optimistic: 14 days
    torrent_alive: 5 # Will reject results with less than 10 seeds
    regexp:
      reject:
        - KORSUB
        - FRENCH
        - SWESUB
        - NLSUB
        - YIFY
        - russian
        - trailer
        - FASTSUB
        - Tamil
        - Hindi
        - romanian
        - arabic
        - russian
        - dutch
    quality: 720p-1080p webdl+ ac3|mp3|aac # Make sure no screeners or cams are downloaded
    list_match:
      from:
        - movie_list: traktmovies
      action: accept
    template: 
      - torrent
    tmdb_lookup: yes
    content_size:
      min: 700
      max: 5000
      strict: no
    set:
      path: /home/pzotac/Downloads/Torrent/Complete/Movies
      content_filename: "{{tmdb_name}} ({{tmdb_year}})"

#  imdb_to_trakt:  # This task adds all the movies in your imdb watchlist to your trakt watchlist
#    imdb_list:
#      login: pascal.holzmann@gmail.com
#      password: Fisch123!
#      list: watchlist
#    accept_all: yes
#    list_add:
#      - trakt_list:
#          username: frozenbubble
#          list: watchlist

  remove stale torrents:
    from_transmission:
      only_complete: yes
    disable: [seen, seen_info_hash]
    transmission:
      action: remove

schedules:
  - tasks: '*'
    interval:
      minutes: 30

web_server:
  bind: 0.0.0.0
  port: 3539
  web_ui: yes
